### ISSUE TITLE
Uncaught ReferenceError: pane is not defined

### ISSUE THREAD

**Issue by skull-squadron** [Floobits/floobits-atom#135] opened 2016-10-24 01:51 UTC
Error occurred during installation
## Location

`{{~}}/.atom/packages/floobits/templates/pane.coffee:6`
## Stack Trace

```
ReferenceError: pane is not defined
    at PaneView.initialize ({{~}}/.atom/packages/floobits/templates/pane.coffee:6:5)
    at PaneView.initialize ({{~}}/.atom/packages/floobits/templates/pane.coffee:1:1)
    at PaneView.View [as constructor] ({{~}}/.atom/packages/floobits/node_modules/space-pen/lib/space-pen.js:184:25)
    at new PaneView ({{~}}/.atom/packages/floobits/templates/pane.coffee:3:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/view-registry.js:134:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/view-registry.js:84:21)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/pane-element.js:132:29)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom-Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom-Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/pane.js:437:21)
    at floobits-welcome_web_view.Proto.load ({{~}}/.atom/packages/floobits/lib/build/webview.js:70:34)
    at Object.welcome ({{~}}/.atom/packages/floobits/lib/floobits.js:83:10)
The error was thrown from the floobits package. You can help by creating an issue. Please explain what actions triggered this error.
Create issue on the floobits package
```

**Comment by ggreer** [comment] 2016-10-25 19:49
Duplicate of #134.

**Closed as completed by ggreer** 2016-10-25 19:49 UTC

**Comment by skull-squadron** [comment] 2016-10-25 19:53
This wasn't a _duplicate_ if it was actually **broken,** it's _resolved_ by an implemented fix.
