### ISSUE TITLE
Conflicts dialog doesn't close after selecting an option

### ISSUE THREAD

**Issue by btipling** [Floobits/floobits-atom#27] opened 2015-03-25 23:52 UTC

**Comment by kans** [comment] 2015-03-26 01:18
Maybe not a bug in case you want to know what it did later?  The buttons can't be pressed again.

**Comment by kans** [comment] 2015-04-01 19:26
fixed by 50557cb9125de3ec73f674d930b7e7a070debca7

**Closed as completed by kans** 2015-04-01 19:26 UTC
