### ISSUE TITLE
Uncaught TypeError: warnUnknownProperty is not a function

### ISSUE THREAD

**Issue by seangates** [Floobits/floobits-atom#123] opened 2016-06-16 18:54 UTC
[Enter steps to reproduce below:]
1. Create a workspace

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.31.3
### Stack Trace

Uncaught TypeError: warnUnknownProperty is not a function

```
At /Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/DOMPropertyOperations.js:120

TypeError: warnUnknownProperty is not a function
    at Object.DOMPropertyOperations.createMarkupForProperty (/Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/DOMPropertyOperations.js:120:7)
    at [object Object].ReactDOMComponent.Mixin._createOpenTagMarkupAndPutListeners (/Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactDOMComponent.js:160:33)
    at [object Object].mountComponent (/Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactDOMComponent.js:119:14)
    at [object Object].mountComponent (/Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:784:44)
    at [object Object].ReactComponent.Mixin._mountComponentIntoNode (/Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactComponent.js:412:25)
    at ReactReconcileTransaction.Mixin.perform (/Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/Transaction.js:141:20)
    at [object Object].ReactComponent.Mixin.mountComponentIntoNode (/Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactComponent.js:388:19)
    at Object._renderNewRootComponent (/Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:313:25)
    at Object.ReactMount.renderComponent (/Users/sgates/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:379:32)
    at floobits-create-workspace.Proto.attachedCallback (/Users/sgates/.atom/packages/floobits/lib/react_wrapper.js:26:28)
    at atom-panel-container.PanelContainerElement.panelAdded (/Applications/Atom.app/Contents/Resources/app.asar/src/panel-container-element.js:46:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PanelContainer.module.exports.PanelContainer.addPanel (/Applications/Atom.app/Contents/Resources/app.asar/src/panel-container.js:69:20)
    at Workspace.module.exports.Workspace.addPanel (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:893:45)
    at Workspace.module.exports.Workspace.addModalPanel (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:869:19)
    at Object.module.exports.addModalPanel (/Users/sgates/.atom/packages/floobits/lib/atom_utils.js:56:33)
    at _create_workspace (/Users/sgates/.atom/packages/floobits/lib/floobits.js:414:19)
    at cb (/Users/sgates/.atom/packages/floobits/lib/floobits.js:417:16)
    at Object.module.exports.create_workspace (/Users/sgates/.atom/packages/floobits/lib/floobits.js:425:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
  2x -5:03.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -5:03.1.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -5:00.3.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -4:59.9.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -4:59.5.0 core:move-left (atom-text-editor.editor.is-focused)
  6x -4:58.3.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -4:56.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:53.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:52.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -4:51.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:51.6.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -4:51.4.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -4:50.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:49.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -4:49.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.0 Floobits: Create Workspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".beans",
      ".cache",
      ".git",
      ".temp",
      "node_modules",
      "static"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "floobits": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.8
atom-html-preview, v0.1.19
autocomplete-css, v0.11.2
autocomplete-html, v0.7.2
autocomplete-marko, v1.0.4
autocomplete-plus, v2.31.0
autocomplete-snippets, v1.11.0
docblockr, v0.7.3
file-icons, v1.7.14
floobits, v0.31.3
language-marko, v1.2.2
linter, v1.11.10
linter-jshint, v2.1.0
linter-php, v1.2.0
minimap, v4.24.6
node-debugger, v1.7.0
project-manager, v2.9.7

# Dev
language-marko, v1.0.7
```

**Comment by ggreer** [comment] 2016-06-24 01:36
While the proptype might be incorrect, this is caused by a bug in Atom: https://github.com/atom/atom/issues/12024. I've submitted a fix (https://github.com/atom/atom/pull/12028), but no idea when it will be merged and put in a release.

I'll work on a workaround.

**Comment by ggreer** [comment] 2016-07-31 07:54
Closing this because the Atom fix was merged.

**Closed as completed by ggreer** 2016-07-31 07:54 UTC
