### ISSUE TITLE
Uncaught Error: [object Object]

### ISSUE THREAD

**Issue by BelphegorPrime** [Floobits/floobits-atom#98] opened 2016-01-17 14:04 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Ubuntu 15.10
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.30.0
### Stack Trace

Uncaught Error: [object Object]

```
At /home/marcel/.atom/packages/floobits/lib/build/edit_perms_view.js:118

Error: [object Object]
    at Object.ajax.error (/home/marcel/.atom/packages/floobits/lib/build/edit_perms_view.js:118:15)
    at fire (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:3099:30)
    at Object.self.fireWith [as rejectWith] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:3211:7)
    at done (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:8266:14)
    at XMLHttpRequest.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:8605:9)
```
### Commands

```
     -1:10.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:09.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:09.4.0 Floobits: Leave Workspace (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -1:05.2.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
  7x -1:02.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:00.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:59.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:59.8.0 Floobits: Create Workspace (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
  3x -0:58.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:58.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:36.9.0 command-palette:toggle (input.chat-input.native-key-bindings)
     -0:33.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -0:33 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:31.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.1.0 Floobits: Permissions (input.chat-input.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10
floobits, v0.30.0
language-lua, v0.9.4
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by ggreer** [comment] 2016-01-30 02:27
Duplicate of #97. But thanks for reporting it!

**Closed as completed by ggreer** 2016-01-30 02:27 UTC
